### ISSUE TITLE
When a line of code is too long, the layout of the page becomes ugly.

### ISSUE THREAD

**Issue by LeeeSe** [Speyll/anemone#10]
<img width="1440" alt="image" src="https://github.com/Speyll/anemone/assets/44465325/b269a0af-a8e1-44fe-9aee-51769b75ebb0">

If I add a line break in the middle of the longest line of code, then the problem goes away

<img width="1440" alt="image" src="https://github.com/Speyll/anemone/assets/44465325/3ee8dc04-45eb-45cd-aebb-cc4f100f6f83">

**Comment by Speyll** [comment]
Thank you for pointing that out! I've just committed the necessary changes to address the issue. The code will now automatically wrap itself as expected. 👍
