### ISSUE TITLE
Error when defining extra.nav_bar following instructions

### ISSUE THREAD

**Issue by astrale-sharp** [Speyll/anemone#11]
Beautiful beautiful theme, loving the colors and style :heart:  

# Instruction followed :
 [here](https://www.getzola.org/themes/anemone/)

# Error : 
``Reason: Variable `nav_item[lang]` not found in context while rendering 'header.html': the evaluated version was `nav_item."en"`. Maybe the index is out of bounds?``

# Description

I believe the following in theme/anemone/config.toml must be added to/adapted when the header must be added.

```
[[extra.header_nav]]
en = { name = "/home/", url = "/" }
fr = { name = "/accueil/", url = "/fr" }

[[extra.header_nav]]
en = { name = "/about/", url = "/about" }
fr = { name = "/concernant/", url = "/about" }

[[extra.header_nav]]
en = { name = "/journal/", url = "/journal" }
fr = { name = "/journal/", url = "/journal" }

[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }
fr = { name = "/blog/", url = "/blog" }
```

# Work Around

copy and adapt this in your config.toml

**Comment by Speyll** [comment]
Thank you for your kind words! 🤗 I've already updated the configuration in the GitHub README, and the config.toml However, please the update process for the Zola website README isn't automatic. I plan to request the Zola team to update the page, but I'm waiting for everything to be somewhat pristine before proceeding.

**Comment by astrale-sharp** [comment]
Perfect then ! :grin:
