### ISSUE TITLE
Code blocks don't fit 80 characters

### ISSUE THREAD

**Issue by colinmarc** [Speyll/anemone#26]
I've generated a bunch of docs from code using your theme, and it looks great!

Unfortunately, it seems like the default width for codeblocks isn't *quite* wide enough to fit 80 characters (80 being a very common max width). I can reflow the comments during generation, but I do kinda think 80 characters is a reasonable width to target.

Here's an example from [this page](https://colinmarc.github.io/magic-mirror/reference/protocol/):

<img width="748" alt="Screenshot 2024-12-13 at 16 49 57" src="https://github.com/user-attachments/assets/3266c759-2408-4844-8f2c-1bdba5628ed1" />

**Comment by Speyll** [comment]
Thank you for the kind words! I’m glad to see people enjoying my theme. The issue should now be resolved without requiring any updates on your end

**Comment by colinmarc** [comment]
Hm, what did you change? I'm still seeing it [here](https://colinmarc.github.io/magic-mirror/reference/protocol/#021-fetch-application-image) for example.

```python
>>> len("  // Required. Must be a complete PNG file and less than 1048576 bytes. Either")
78
```

Thanks for the quick response!
