### ISSUE TITLE
How to move toc underneath title?

### ISSUE THREAD

**Issue by Mateiadrielrafael** [Speyll/anemone#6]
Is there a way to include a `# Heading` above the table of contents? I usually want my title to be above it. In particular, it would be awesome if there was a way to choose an arbitrary location for the table of contents.

**Comment by Mateiadrielrafael** [comment]
Hmm, it seems like the `header` block is not used in `base.html` for some reason

**Comment by throwaway69420-69420** [comment]
@Mateiadrielrafael hello, can you link your website git repo here? Perhaps I can learn from it, I am a beginner at zola

**Comment by Mateiadrielrafael** [comment]
@throwaway69420-69420 Hi! My repo is not public

**Comment by throwaway69420-69420** [comment]
do you plan on making it public sometime soon? @Mateiadrielrafael

**Comment by Mateiadrielrafael** [comment]
I don't know. I feel like this is not a good place to discuss this @throwaway69420-69420

**Comment by throwaway69420-69420** [comment]
thank you for your time @Mateiadrielrafael :)
